export { default as Landing } from './Landing';
export { default as Drinks} from './Drinks';
export { default as Drink} from './Drink';
export { default as Meals} from './Meals';
export { default as Meal} from './Meal';
export { default as About } from './About';
export { default as Cocktail } from './Cocktail';
export { default as Newsletter } from './Newsletter';
export { default as HomeLayout } from './HomeLayout';
export { default as Error } from './Error';
export { default as SinglePageError } from './SinglePageError';
